In [7]:
import numpy as np
from numpy import linalg as la

A = np.array([[-6, 7, 8],
              [7, -8, 9],
              [8, 9, -10]])

B = np.array([[0, 1, 2],
              [1, 2, 3],
              [2, 3, 4]])

C = np.array([[-10, 9, 8],
              [9, -8, 7],
              [8, 7, -12]])

In [8]:
B_A = B - A
A_C = A - C
w_BA,_ = la.eig(B_A)
w_AC,_ = la.eig(A_C)

In [13]:
# check symmetry
print(B_A)
print(A_C)

[[ 6 -6 -6]
 [-6 10 -6]
 [-6 -6 14]]
[[ 4 -2  0]
 [-2  0  2]
 [ 0  2  2]]


In [14]:
print('Eigenvalues B - A', w_BA)
print('Eigenvalues A - C', w_AC)

Eigenvalues B - A [-2.58300524 14.         18.58300524]
Eigenvalues A - C [-1.75877048  5.06417777  2.69459271]
